### PR TITLE
[KFI]fix(default-content-types): enums array

### LINKED ISSUE #32: [default-content-types] Priority and Status field declarations
This is the response from a content update:
```
    "Name": "Duis commodo nunc",
    "StartDate": "0001-01-01T00:00:00",
    "DueDate": "2015-11-30T01:00:00Z",
    "AssignedTo": {
      "__deferred": {
        "uri": "/odata.svc/workspaces/Project/budapestprojectworkspace/Tasks('Duis commodo nunc')/AssignedTo"
      }
    },
    "Priority": [
      "1"
    ],
    "Status": [
      "active"
    ]
```
Priority and Status fields are arrays. But in the declaration file those are enums.
```
export declare class Task extends ListItem {
    StartDate?: string;
    DueDate?: string;
    AssignedTo?: ContentListReferenceField<User>;
    Priority?: Priority;
    Status?: Status;
    TaskCompletion?: number;
    RemainingDays?: number;
    DueText?: string;
    DueCssClass?: string;
}
```

### PR DESCRIPTION
**Pull request by B3zo0**
Enum values are coming back as enum arrays from the server

fixes #32

### CODE REVIEW

File: packages/sn-redux/test/ReducersTests.ts [hunk 1]
```diff
@@ -265,7 +265,7 @@ describe('Reducers', () => {
           Name: 'SomeArtice',
```
Comment (herflis) [inline packages/sn-redux/test/ReducersTests.ts]:
```suggestion
          Name: 'SomeArticle',
```

File: packages/sn-redux/test/ReducersTests.ts [hunk 2]
```diff
@@ -355,7 +355,7 @@ describe('Reducers', () => {
...
```
Comment (herflis) [inline packages/sn-redux/test/ReducersTests.ts]:
```suggestion
          Name: 'SomeArticle',
```

File: packages/sn-redux/test/ReducersTests.ts [hunk 3]
```diff
@@ -507,7 +507,7 @@ describe('Reducers', () => {
...
```
Comment (herflis) [inline packages/sn-redux/test/ReducersTests.ts]:
```suggestion
          Name: 'SomeArticle',
```

File: packages/sn-redux/test/ReducersTests.ts [hunk 4]
```diff
@@ -535,7 +535,7 @@ describe('Reducers', () => {
...
```
Comment (herflis) [inline packages/sn-redux/test/ReducersTests.ts]:
```suggestion
          Name: 'SomeArticle',
```
